// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4474556114866037831),
    name: 'Message',
    lastPropertyId: const obx_int.IdUid(7, 3884359174668553763),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4374911172230848726),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5540394507905696390),
        name: 'senderName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5613918372238258233),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 178536767504035108),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6247984395395132577),
        name: 'isMe',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6899575286442871341),
        name: 'isFile',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3884359174668553763),
        name: 'filePath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 496248704256147949),
    name: 'Peer',
    lastPropertyId: const obx_int.IdUid(4, 1261741253320118700),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3208000778846902382),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1749778504502845243),
        name: 'name',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 403353450604213686),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6991570865962514879),
        name: 'ip',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1261741253320118700),
        name: 'isPaired',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 496248704256147949),
    lastIndexId: const obx_int.IdUid(1, 403353450604213686),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Message: obx_int.EntityDefinition<Message>(
      model: _entities[0],
      toOneRelations: (Message object) => [],
      toManyRelations: (Message object) => {},
      getId: (Message object) => object.id,
      setId: (Message object, int id) {
        object.id = id;
      },
      objectToFB: (Message object, fb.Builder fbb) {
        final senderNameOffset = fbb.writeString(object.senderName);
        final contentOffset = fbb.writeString(object.content);
        final filePathOffset = object.filePath == null
            ? null
            : fbb.writeString(object.filePath!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, senderNameOffset);
        fbb.addOffset(2, contentOffset);
        fbb.addInt64(3, object.timestamp.millisecondsSinceEpoch);
        fbb.addBool(4, object.isMe);
        fbb.addBool(5, object.isFile);
        fbb.addOffset(6, filePathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final senderNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final isMeParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final isFileParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final object = Message(
          senderName: senderNameParam,
          content: contentParam,
          timestamp: timestampParam,
          filePath: filePathParam,
          isMe: isMeParam,
          isFile: isFileParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    Peer: obx_int.EntityDefinition<Peer>(
      model: _entities[1],
      toOneRelations: (Peer object) => [],
      toManyRelations: (Peer object) => {},
      getId: (Peer object) => object.id,
      setId: (Peer object, int id) {
        object.id = id;
      },
      objectToFB: (Peer object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final ipOffset = fbb.writeString(object.ip);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, ipOffset);
        fbb.addBool(3, object.isPaired);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final ipParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final isPairedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final object = Peer(
          name: nameParam,
          ip: ipParam,
          isPaired: isPairedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Message] entity fields to define ObjectBox queries.
class Message_ {
  /// See [Message.id].
  static final id = obx.QueryIntegerProperty<Message>(
    _entities[0].properties[0],
  );

  /// See [Message.senderName].
  static final senderName = obx.QueryStringProperty<Message>(
    _entities[0].properties[1],
  );

  /// See [Message.content].
  static final content = obx.QueryStringProperty<Message>(
    _entities[0].properties[2],
  );

  /// See [Message.timestamp].
  static final timestamp = obx.QueryDateProperty<Message>(
    _entities[0].properties[3],
  );

  /// See [Message.isMe].
  static final isMe = obx.QueryBooleanProperty<Message>(
    _entities[0].properties[4],
  );

  /// See [Message.isFile].
  static final isFile = obx.QueryBooleanProperty<Message>(
    _entities[0].properties[5],
  );

  /// See [Message.filePath].
  static final filePath = obx.QueryStringProperty<Message>(
    _entities[0].properties[6],
  );
}

/// [Peer] entity fields to define ObjectBox queries.
class Peer_ {
  /// See [Peer.id].
  static final id = obx.QueryIntegerProperty<Peer>(_entities[1].properties[0]);

  /// See [Peer.name].
  static final name = obx.QueryStringProperty<Peer>(_entities[1].properties[1]);

  /// See [Peer.ip].
  static final ip = obx.QueryStringProperty<Peer>(_entities[1].properties[2]);

  /// See [Peer.isPaired].
  static final isPaired = obx.QueryBooleanProperty<Peer>(
    _entities[1].properties[3],
  );
}
